import { Feather, Ionicons } from "@expo/vector-icons";
import { useEffect, useRef, useState } from "react";
import { ActivityIndicator, ScrollView, Text, View } from "react-native";
import Animated from "react-native-reanimated";

import { AddItemField } from "@/components/AddItemField";
import { BottomSheet } from "@/components/BottomSheet";
import { IconButton, PrimaryButton } from "@/components/Button";
import { ChecklistRow } from "@/components/ChecklistRow";
import { Chip } from "@/components/Chip";
import { listItemEntering, listItemLayout } from "@/constants/theme";
import { useRtlText } from "@/hooks/useRtlText";
import { useColors } from "@/hooks/useTheme";
import { useTranslation } from "@/hooks/useTranslation";
import type { PlanStep } from "@/lib/ai/types";
import type { StepDraft, Task } from "@/types/task";

// A step added by hand, until the task's steps say otherwise (as addSubtask).
const NEW_STEP_MINUTES = 10;

function newStepId(index = 0): string {
  return `subtask-${Date.now().toString(36)}-${index}-${Math.random().toString(36).slice(2, 6)}`;
}

/** The task's steps as they are now, in order — where the draft starts. */
function draftOf(task: Task): StepDraft[] {
  return (task.subtasks ?? [])
    .slice()
    .sort((a, b) => a.order - b.order)
    .map((subtask) => ({
      id: subtask.id,
      label: subtask.label,
      estimatedMinutes: subtask.estimatedMinutes,
      completed: subtask.status === "completed",
    }));
}

/**
 * The AI's steps in place of the unfinished ones it was shown; the ones
 * already done stay, first. A step added while it worked (not in `sentIds`)
 * is the user's own and stays too, after the AI's.
 */
function withNewSteps(draft: StepDraft[], steps: PlanStep[], sentIds: Set<string>): StepDraft[] {
  return [
    ...draft.filter((step) => step.completed),
    ...steps.map((step, index) => ({
      id: newStepId(index),
      label: step.title,
      estimatedMinutes: step.estimatedMinutes,
      completed: false,
    })),
    ...draft.filter((step) => !step.completed && !sentIds.has(step.id)),
  ];
}

/**
 * The "AI Breakdown" sheet: the task's steps, which can be checked off,
 * regenerated by the AI, removed one by one, or added to by hand. Laid out
 * like Task Details' subtasks — the same rows, the same field to add one.
 *
 * Everything here is a draft until "Confirm these steps" (the user's call,
 * 2026-10-08): closing the sheet any other way — ✕, the scrim, Back — leaves
 * the task's steps exactly as they were.
 */
export function BreakdownSheet({
  visible,
  task,
  status,
  autoGenerate,
  onGenerate,
  onConfirm,
  onClose,
}: {
  visible: boolean;
  task: Task;
  status: "idle" | "loading" | "error";
  /** Ask the AI for steps straight away — the task has none left to do. */
  autoGenerate: boolean;
  /** New steps from the AI for the work this draft has left (useTaskAiAssist), or null. */
  onGenerate: (draft: StepDraft[]) => Promise<PlanStep[] | null>;
  /** The steps to save. */
  onConfirm: (steps: StepDraft[]) => void;
  /** Closed without confirming: nothing is saved. */
  onClose: () => void;
}) {
  const colors = useColors();
  const t = useTranslation();
  const rtl = useRtlText();
  // A new sheet starts from the task as it is (it's mounted fresh each time
  // it opens — see NextTaskCard).
  const [steps, setSteps] = useState(() => draftOf(task));
  const [stepDraft, setStepDraft] = useState("");
  const isLoading = status === "loading";

  const generate = async () => {
    const sentIds = new Set(steps.map((step) => step.id));
    const next = await onGenerate(steps);
    if (next) setSteps((current) => withNewSteps(current, next, sentIds));
  };

  // Once, as the sheet opens.
  const autoStarted = useRef(false);
  useEffect(() => {
    if (!autoGenerate || autoStarted.current) return;
    autoStarted.current = true;
    void generate();
  });

  const addStep = (current: StepDraft[]): StepDraft[] => {
    const label = stepDraft.trim();
    if (!label) return current;
    return [...current, { id: newStepId(current.length), label, estimatedMinutes: NEW_STEP_MINUTES, completed: false }];
  };

  const handleAddStep = () => {
    setSteps(addStep);
    setStepDraft("");
  };

  const handleToggle = (id: string) =>
    setSteps((current) => current.map((step) => (step.id === id ? { ...step, completed: !step.completed } : step)));

  const handleDelete = (id: string) => setSteps((current) => current.filter((step) => step.id !== id));

  // A step still being typed counts too, as if added first.
  const handleConfirm = () => onConfirm(addStep(steps));

  return (
    <BottomSheet
      visible={visible}
      onClose={onClose}
      title={t.breakdown.eyebrow}
      // Orange only because it's the AI's own sparkle.
      titleIcon={<Ionicons name="sparkles" size={14} color={colors.orange[500]} />}
      closeLabel={t.breakdown.close}
    >
      <Text className="font-grotesk-semibold text-[17px] leading-[22px] text-ink-cream" style={rtl}>
        {task.title}
      </Text>

      <View className="mt-4 flex-row items-center justify-between gap-3">
        <Text className="font-grotesk-medium text-sm text-ink-cream-muted">{t.breakdown.steps(steps.length)}</Text>
        <Chip
          label={isLoading ? t.breakdown.generating : t.breakdown.regenerate}
          onPress={() => void generate()}
          disabled={isLoading}
          icon={(color) =>
            isLoading ? (
              <ActivityIndicator size="small" color={colors.orange[500]} />
            ) : (
              <Feather name="refresh-cw" size={14} color={color} />
            )
          }
        />
      </View>

      {status === "error" ? (
        <Text className="mt-3 font-grotesk-medium text-sm text-overdue-500">{t.common.aiUnreachable}</Text>
      ) : null}

      <ScrollView
        // Shrinks so a long list scrolls inside the sheet instead of
        // pushing the confirm button past its bottom edge.
        style={{ flexGrow: 0, flexShrink: 1, marginTop: 12 }}
        contentContainerStyle={{ gap: 8 }}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        {steps.length === 0 && isLoading ? (
          <View className="flex-row items-center justify-center gap-2.5 py-6">
            <ActivityIndicator size="small" color={colors.orange[500]} />
            <Text className="font-grotesk-medium text-sm text-ink-cream-muted">{t.breakdown.breakingDown}</Text>
          </View>
        ) : null}

        {steps.map((step, index) => (
          <Animated.View key={step.id} entering={listItemEntering(index)} layout={listItemLayout()}>
            <ChecklistRow label={step.label} checked={step.completed} onToggle={() => handleToggle(step.id)}>
              <IconButton
                icon="trash-2"
                onPress={() => handleDelete(step.id)}
                accessibilityLabel={t.taskDetail.deleteSubtask(step.label)}
              />
            </ChecklistRow>
          </Animated.View>
        ))}

        <AddItemField
          value={stepDraft}
          onChangeText={setStepDraft}
          onAdd={handleAddStep}
          placeholder={t.breakdown.stepPlaceholder}
          addLabel={t.breakdown.addStep}
        />
      </ScrollView>

      <PrimaryButton
        icon="check"
        size="lg"
        label={t.breakdown.confirm}
        onPress={handleConfirm}
        disabled={isLoading}
        className="mt-4"
      />
    </BottomSheet>
  );
}
