import { Feather, Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { ActivityIndicator, ScrollView, Text, View } from "react-native";
import Animated from "react-native-reanimated";

import { AddItemField } from "@/components/AddItemField";
import { BottomSheet } from "@/components/BottomSheet";
import { IconButton, PrimaryButton } from "@/components/Button";
import { ChecklistRow } from "@/components/ChecklistRow";
import { Chip } from "@/components/Chip";
import { listItemEntering, listItemLayout } from "@/constants/theme";
import { useRtlText } from "@/hooks/useRtlText";
import { useColors } from "@/hooks/useTheme";
import { useTranslation } from "@/hooks/useTranslation";
import { useTaskStore } from "@/store/useTaskStore";
import type { Task } from "@/types/task";

/**
 * The "AI Breakdown" sheet: the task's steps, which can be checked off,
 * regenerated by the AI, removed one by one, or added to by hand. Laid out
 * like Task Details' subtasks — the same rows, the same field to add one.
 */
export function BreakdownSheet({
  visible,
  task,
  status,
  onRegenerate,
  onToggleStep,
  onClose,
}: {
  visible: boolean;
  task: Task;
  status: "idle" | "loading" | "error";
  onRegenerate: () => void;
  /** Goes through the session runner, so finishing the last step advances the session. */
  onToggleStep: (subtaskId: string) => void;
  onClose: () => void;
}) {
  const colors = useColors();
  const t = useTranslation();
  const rtl = useRtlText();
  const addSubtask = useTaskStore((state) => state.addSubtask);
  const deleteSubtask = useTaskStore((state) => state.deleteSubtask);
  const [stepDraft, setStepDraft] = useState("");

  const steps = task.subtasks?.slice().sort((a, b) => a.order - b.order) ?? [];
  const isLoading = status === "loading";

  const handleAddStep = () => {
    const label = stepDraft.trim();
    if (label) addSubtask(task.id, label);
    setStepDraft("");
  };

  // The steps are already on the task as they're generated or added, so
  // confirming just settles a step still being typed and closes the sheet —
  // it's the "this is my plan" moment, not a save.
  const handleConfirm = () => {
    handleAddStep();
    onClose();
  };

  return (
    <BottomSheet
      visible={visible}
      onClose={onClose}
      title={t.breakdown.eyebrow}
      // Orange only because it's the AI's own sparkle.
      titleIcon={<Ionicons name="sparkles" size={14} color={colors.orange[500]} />}
      closeLabel={t.breakdown.close}
    >
      <Text className="font-grotesk-semibold text-[17px] leading-[22px] text-ink-cream" style={rtl}>
        {task.title}
      </Text>

      <View className="mt-4 flex-row items-center justify-between gap-3">
        <Text className="font-grotesk-medium text-sm text-ink-cream-muted">{t.breakdown.steps(steps.length)}</Text>
        <Chip
          label={isLoading ? t.breakdown.generating : t.breakdown.regenerate}
          onPress={onRegenerate}
          disabled={isLoading}
          icon={(color) =>
            isLoading ? (
              <ActivityIndicator size="small" color={colors.orange[500]} />
            ) : (
              <Feather name="refresh-cw" size={14} color={color} />
            )
          }
        />
      </View>

      {status === "error" ? (
        <Text className="mt-3 font-grotesk-medium text-sm text-overdue-500">{t.common.aiUnreachable}</Text>
      ) : null}

      <ScrollView
        // Shrinks so a long list scrolls inside the sheet instead of
        // pushing the confirm button past its bottom edge.
        style={{ flexGrow: 0, flexShrink: 1, marginTop: 12 }}
        contentContainerStyle={{ gap: 8 }}
        keyboardShouldPersistTaps="handled"
        showsVerticalScrollIndicator={false}
      >
        {steps.length === 0 && isLoading ? (
          <View className="flex-row items-center justify-center gap-2.5 py-6">
            <ActivityIndicator size="small" color={colors.orange[500]} />
            <Text className="font-grotesk-medium text-sm text-ink-cream-muted">{t.breakdown.breakingDown}</Text>
          </View>
        ) : null}

        {steps.map((step, index) => (
          <Animated.View key={step.id} entering={listItemEntering(index)} layout={listItemLayout()}>
            <ChecklistRow label={step.label} checked={step.status === "completed"} onToggle={() => onToggleStep(step.id)}>
              <IconButton
                icon="trash-2"
                onPress={() => deleteSubtask(task.id, step.id)}
                accessibilityLabel={t.taskDetail.deleteSubtask(step.label)}
              />
            </ChecklistRow>
          </Animated.View>
        ))}

        <AddItemField
          value={stepDraft}
          onChangeText={setStepDraft}
          onAdd={handleAddStep}
          placeholder={t.breakdown.stepPlaceholder}
          addLabel={t.breakdown.addStep}
        />
      </ScrollView>

      <PrimaryButton
        icon="check"
        size="lg"
        label={t.breakdown.confirm}
        onPress={handleConfirm}
        disabled={isLoading || (steps.length === 0 && stepDraft.trim().length === 0)}
        className="mt-4"
      />
    </BottomSheet>
  );
}
